"""full schema v1

Revision ID: 1b7038a56b13
Revises: 5e865c1d69c3
Create Date: 2026-08-25 12:00:00
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b7038a56b13'
down_revision = '5e865c1d69c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('razorpay_key_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('customers',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_table('payments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.Column('payment_method', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_external_id', 'payments', ['external_id'], unique=False)
    op.create_table('subscriptions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('payment_id', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_external_id', 'subscriptions', ['external_id'], unique=False)
    op.create_table('invoices',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invoices_external_id', 'invoices', ['external_id'], unique=False)
    op.create_table('checkout_sessions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('external_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checkout_sessions_external_id', 'checkout_sessions', ['external_id'], unique=False)
    op.create_table('revenue_opportunities',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('merchant_id', sa.String(), nullable=False),
        sa.Column('customer_id', sa.String(), nullable=True),
        sa.Column('source_type', sa.String(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=True),
        sa.Column('amount_at_risk', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('currency', sa.String(length=3), nullable=False),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('group', sa.String(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
        sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_scores',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('opportunity_id', sa.String(), nullable=False),
        sa.Column('model_version', sa.String(), nullable=False),
        sa.Column('recoverability_score', sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column('expected_recovery', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('priority_score', sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column('features_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['opportunity_id'], ['revenue_opportunities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('opportunity_id', sa.String(), nullable=False),
        sa.Column('action_type', sa.String(), nullable=False),
        sa.Column('decision_reason', sa.Text(), nullable=True),
        sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('policy_status', sa.String(), nullable=False),
        sa.Column('external_ref', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['opportunity_id'], ['revenue_opportunities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcomes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('intervention_id', sa.String(), nullable=True),
        sa.Column('opportunity_id', sa.String(), nullable=False),
        sa.Column('payment_status', sa.String(), nullable=False),
        sa.Column('recovered_amount', sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column('event_id', sa.String(), nullable=True),
        sa.Column('observed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
        sa.ForeignKeyConstraint(['opportunity_id'], ['revenue_opportunities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('treatment_percent', sa.Integer(), nullable=True),
        sa.Column('metric', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_assignments',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('experiment_id', sa.String(), nullable=False),
        sa.Column('opportunity_id', sa.String(), nullable=False),
        sa.Column('variant', sa.String(), nullable=False),
        sa.Column('assigned_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
        sa.ForeignKeyConstraint(['opportunity_id'], ['revenue_opportunities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence_events',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('opportunity_id', sa.String(), nullable=False),
        sa.Column('intervention_id', sa.String(), nullable=True),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('actor', sa.String(), nullable=False),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('before_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('after_state', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], ),
        sa.ForeignKeyConstraint(['opportunity_id'], ['revenue_opportunities.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_performance',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('segment_id', sa.String(), nullable=True),
        sa.Column('failure_type', sa.String(), nullable=True),
        sa.Column('action_type', sa.String(), nullable=True),
        sa.Column('total_attempts', sa.Integer(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('avg_lift', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Alter raw_events to add new columns (with server_default for processed)
    op.add_column('raw_events', sa.Column('processed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('raw_events', sa.Column('normalized_event_id', sa.String(), nullable=True))
    op.add_column('raw_events', sa.Column('opportunity_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'raw_events', 'revenue_opportunities', ['opportunity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_events', type_='foreignkey')
    op.drop_column('raw_events', 'opportunity_id')
    op.drop_column('raw_events', 'normalized_event_id')
    op.drop_column('raw_events', 'processed')
    op.drop_table('strategy_performance')
    op.drop_table('evidence_events')
    op.drop_table('experiment_assignments')
    op.drop_table('experiments')
    op.drop_table('outcomes')
    op.drop_table('interventions')
    op.drop_table('opportunity_scores')
    op.drop_table('revenue_opportunities')
    op.drop_table('checkout_sessions')
    op.drop_table('invoices')
    op.drop_table('subscriptions')
    op.drop_table('payments')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###