"""create raw_events table

Revision ID: 5e865c1d69c3
Revises: 
Create Date: 2026-08-25 07:39:28.910491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e865c1d69c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_events_event_type'), 'raw_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_type'), table_name='raw_events')
    op.drop_table('raw_events')
    # ### end Alembic commands ###
